import { FormContextProvider } from "./FormContext";
import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";
import FormNav from "./Components/FormNav";

const ubuntuRegular = Ubuntu({
  weight: "400",
  variable: "--font-ubuntu",
  subsets: ["latin"],
});

const ubuntuMedium = Ubuntu({
  weight: "500",
  variable: "--font-ubuntu",
  subsets: ["latin"],
});

const ubuntuBold = Ubuntu({
  weight: "700",
  variable: "--font-ubuntu",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${styles.body} ${ubuntuRegular.variable} ${ubuntuMedium.variable} ${ubuntuBold.variable} antialiased`}
      >
        <FormContextProvider>
          <div className={styles.card}>
            <FormNav />
            <div className={styles.children}>{children}</div>
          </div>
        </FormContextProvider>
      </body>
    </html>
  );
}
